# This is a basic workflow to help you get started with Actions

name: Build & Release Resource Pack

permissions:
  contents: write

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare dist folder
        run: mkdir -p dist

      - name: Zip all files respecting .gitignore
        run: |
          # List files for debugging
          git ls-files
          # Zip only tracked files (ignores files in .gitignore)
          git ls-files -z | xargs -0 zip -r dist/pack.zip

      - name: Compute SHA-1
        run: |
          sha1sum dist/pack.zip > dist/pack.sha1
          # This writes "<sha1>  dist/pack.zip"

      - name: Create GitHub Release (or upload asset)
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: dist/pack.zip
          updateOnlyUnreleased: false
          makeLatest: true
          # optionally include pack.sha1 as additional asset or in release notes
